site_name: jan-ken-fw
site_description: Rock Paper Scissors game API.
repo_url: https://github.com/Razhelq/jan-ken-fw
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Razhelq">Razhelq</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
